config/routes.rb
Rails.application.routes.draw do

  resources :areas
  resources :category_types
  resources :courses do
    collection do
     get :search
     get :autocomplete
    end
  end
  resources :companies do
    resources :employees
  end

  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: "omniauth_callbacks" }

  root to: 'pages#index'
  get 'about'   => 'pages#about'
  get 'terms'   => 'pages#terms'
  get 'policy'   => 'pages#policy'
  get 'be_company' => 'pages#be_company'
  get 'faq'   => 'pages#faq'
  get 'support'   => 'pages#support'
  get 'steps'   => 'pages#steps'
end

app/models/company.rb
class Company < ActiveRecord::Base
  usar_como_cnpj :cnpj
  validates :name, presence: true
  has_many :enderecos
  has_many :courses
  has_many :employees, dependent: :destroy
  accepts_nested_attributes_for :enderecos, :reject_if => :all_blank, :allow_destroy => true
  has_and_belongs_to_many :category_types
  belongs_to :user

  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :owned_company, only: [:edit, :update, :destroy]

  @category_types = CategoryType.all
  # GET /companies
  # GET /companies.json
  def index
    if current_user.admin?
      @companies = Company.all
    else
      @companies = Company.where user_id: current_user.id
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    #@company = Company.new
    @company = current_user.companies.build
    # 3.times { @company.enderecos.build }
  end

  # GET /companies/1/edit
  def edit
    #@company = Company.find(params[:id])
    #@company.enderecos.build
  end

  # POST /companies
  # POST /companies.json
  def create
    #@company = Company.new(company_params)
    @company = current_user.companies.build(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Parceiro criado com sucesso.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Parceiro atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Parceiro apagado com sucesso.' }
      format.json { head :no_content }
    end
  end

  def localizar_endereco
    # Classe do brazilian-rails responsavél pela busca de endereco.
    @endereco = BuscaEndereco.cep params[:cep]
    endereco = @endereco.fetch(0)
    numero = @endereco.fetch(1)
    bairro = @endereco.fetch(2)
    estado = @endereco.fetch(3)
    cidade = @endereco.fetch(4)
  end

  private

    def owned_company
      unless current_user.id == @company.user_id || current_user.admin?
        flash[:alert] = "Somente administradores e usuários master podem editar o Parceiro"
        redirect_to root_path
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:cnpj, :name, :phone, :contact, :email, :site,
                            :user_id, :marketing,  :category_type_ids => [],
                            enderecos_attributes: [:id, :nome, :cep, :cidade, :estado,
                            :bairro, :logradouro, :numero, :_destroy])
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= simple_form_for(@company) do |f| %>
  <%= f.error_notification %>


  <div class="form-group">
    <%= f.input :cnpj , class: 'form-control'%>
  </div>
  <div class="form-group">
    <%= f.input :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.input :phone, class: 'form-control'%>
  </div>
  <div class="form-group">
    <%= f.input :email, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.association :user, class: 'form-control', :disabled => true %>
  </div>
  <div class="form-group">
    <%= f.association :category_types , label_method: :select_label, class: 'form-control' %>
    <small class="text-muted">Use o <kbd>CTRL</kbd> para selecionar mais de uma área.</small>
  </div>
  <div class="form-group">
    <%= f.input :site, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.input :contact, class: 'form-control'%>
  </div>
  <div class="form-group">
    <%= f.input :marketing, class: 'form-control'%>
  </div>

  <br>
  <h3>Endereços: </h3><br>
  <div class="enderecos">
    <%= f.fields_for :enderecos do |e| %>
      <%= render 'enderecos/endereco_fields', f: e %>
    <% end %>
    <%= link_to_add_association "Adicionar Endereço", f, :enderecos,
            partial: 'enderecos/endereco_fields', class: "btn btn-default" %>
  </div>

  <br>
  <%= f.submit "Salvar", class: 'btn btn-primary form-control' %>

<% end %>

app/views/companies/edit.html.erb
<%= render "shared/formbg_header" %>

  <div class="panel-heading">
    <h2> Editar Parceiro </h2>
  </div>
  <div class="panel-body">

    <%= render 'form' %>
    <br>
    <%= link_to 'Exibir', @company, class: 'btn btn-link btn-sm' %>
    <%= link_to 'Voltar', companies_path, class: 'btn btn-link btn-sm' %>

  </div>

<%= render "shared/formbg_footer" %>

app/views/companies/index.html.erb
<div class="form panel">
  <div class="row">
    <div class= "col-md-6 col-md-offset-3">
      <div class="table-responsive">
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Nome</th>
              <th>Cnpj</th>
              <th>Fone</th>
              <th>Contato</th>
            </tr>
          </thead>

          <tbody>
            <% @companies.each do |company| %>
              <tr>
                <td><%= link_to company.name , company%></td>
                <td><%= company.cnpj %></td>
                <td><%= company.phone %></td>
                <td><%= company.contact %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= link_to "Novo Parceiro",  new_company_path, class: 'btn btn-primary btn-md' %>
      </div>
    </div>
  </div>
</div>

app/views/companies/new.html.erb
<%= render "shared/formbg_header" %>

  <div class="panel-heading">
    <h2> Novo Parceiro </h2>
  </div>
  <div class="panel-body">

    <%= render 'form' %>
    <br>
    <%= link_to 'Voltar', companies_path, class: 'btn btn-link btn-sm' %>

  </div>

<%= render "shared/formbg_footer" %>

app/views/companies/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-push-3">
      <p class="name-company">
        <%= @company.name %>
      <p>
      <div class="divider-4px-yellow"></div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-6 col-sm-push-3">
      <p class="subtitle-company"> Dados Cadastrais<p>
      <div class="divider-2px-blue"></div>
      <p><strong>CNPJ:</strong> <%= @company.cnpj %> </p>
      <p><strong>Fone:</strong> <%= @company.phone %> </p>
      <p><strong>Site:</strong> <%= @company.site %> </p>
      <p><strong>E-mail:</strong> <%= @company.email %> </p>
      <p><strong>Contato:</strong> <%= @company.contact %> </p>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-6 col-sm-push-3">
      <p class="subtitle-company"> Endereços <p>
      <div class="divider-2px-blue"></div>
      <% @company.enderecos.each do |endereco| %>
        <p><strong>Id:</strong> <%= endereco.nome %> </p>
        <p><strong>Logradouro:</strong> <%= endereco.logradouro %> <%= endereco.numero %> </p>
        <p><strong>Bairro:</strong> <%= endereco.bairro %> </p>
        <p><strong>Cidade:</strong> <%= endereco.cidade %> <%= endereco.estado %> </p>
        <p><strong>CEP:</strong> <%= endereco.cep %> </p>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-6 col-sm-push-3">
      <% if @company.user_id == current_user.id || current_user.admin? %>
        <p class="subtitle-company"> Usuários Autorizados<p>
        <div class="divider-2px-blue"></div>
        <% if @company.employees %>
          <% @company.employees.each do |employee| %>
            <p>
              <%= employee.email %>
              <%= link_to '', company_employee_path(@company, employee),
                              class: 'glyphicon glyphicon-remove',
                              method: :delete, data: { confirm: "Tem certeza?" } %>
            </p>
          <% end %>
        <% end %>

        <div class="space40"></div>

        <%= simple_form_for [@company, @company.employees.new] do |f| %>
          <%= f.error_notification %>

          <div class="form-group form-employee">
            <%= f.input :email, class: 'form-control'%>
          </div>
          <div class="form-actions">
            <%= f.button :submit, "Adicionar", class: 'btn btn-primary btn-sm btn-add'  %>
            <%= link_to 'Editar', edit_company_path(@company), class: 'btn btn-default btn-sm btn-edit' %> |
            <%= link_to 'Deletar', @company, class: 'btn btn-danger btn-sm btn-delete',
                                method: :delete, data: { confirm: 'Tem certeza?' } %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="space60"></div>
  <div class="row">
    <div class="col-sm-6 col-sm-push-3">
      <%= link_to 'Voltar', companies_path, class: 'btn btn-lg btn-company-back' %>
    </div>
  </div>
  <div class="space120"></div>
</div>