config/routes.rb
Rails.application.routes.draw do

  resources :areas
  resources :category_types
  resources :courses do
    collection do
     get :search
     get :autocomplete
    end
  end
  resources :companies do
    resources :employees
  end

  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: "omniauth_callbacks" }

  root to: 'pages#index'
  get 'about'   => 'pages#about'
  get 'terms'   => 'pages#terms'
  get 'policy'   => 'pages#policy'
  get 'be_company' => 'pages#be_company'
  get 'faq'   => 'pages#faq'
  get 'support'   => 'pages#support'
  get 'steps'   => 'pages#steps'
end

app/models/area.rb
class Area < ActiveRecord::Base
  validates :name,  presence: true, length: { maximum: 50}

  has_and_belongs_to_many :courses
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :owned_area, only: [:edit, :update, :destroy]

  # GET /areas
  # GET /areas.json
  def index
    @areas = Area.all
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
  end

  # GET /areas/new
  def new
    @area = Area.new
  end

  # GET /areas/1/edit
  def edit
  end

  # POST /areas
  # POST /areas.json
  def create
    @area = Area.new(area_params)

    respond_to do |format|
      if @area.save
        format.html { redirect_to @area, notice: 'Area criada com sucesso.' }
        format.json { render :show, status: :created, location: @area }
      else
        format.html { render :new }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /areas/1
  # PATCH/PUT /areas/1.json
  def update
    respond_to do |format|
      if @area.update(area_params)
        format.html { redirect_to @area, notice: 'Area atualizada com sucesso..' }
        format.json { render :show, status: :ok, location: @area }
      else
        format.html { render :edit }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    @area.destroy
    respond_to do |format|
      format.html { redirect_to areas_url, notice: 'Area deletada com sucesso.' }
      format.json { head :no_content }
    end
  end

  private

    def owned_area
      unless current_user.admin?
        flash[:alert] = "Somente administradores e usuários master podem editar as areas"
        redirect_to root_path
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_area
      @area = Area.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def area_params
      params.require(:area).permit(:name)
    end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/views/areas/_form.html.erb
<%= simple_form_for(@area) do |f| %>
  <%= f.error_notification %>
  <div class="form-group">
    <%= f.input :name , class: 'form-control' %>
  </div>

  <br>
  <%= f.submit "Salvar", class: 'btn btn-primary form-control' %>
<% end %>

app/views/areas/edit.html.erb
<%= render "shared/formbg_header" %>

  <div class="panel-heading">
    <h2> Editar Area </h2>
  </div>
  <div class="panel-body">

    <%= render 'form' %>

    <br>
    <%= link_to 'Exibir', @area, class: 'btn btn-link btn-sm' %> |
    <%= link_to 'Voltar', areas_path, class: 'btn btn-link btn-sm' %>

  </div>

<%= render "shared/formbg_footer" %>

app/views/areas/index.html.erb
<h1>Areas</h1>

<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Nome</th>
      </tr>
    </thead>

    <tbody>
      <% @areas.each do |area| %>
        <tr>
          <td><%= link_to area.name , area%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

<%= link_to "Nova Area",  new_area_path, class: 'btn btn-default btn-sm' %>

app/views/areas/new.html.erb
<%= render "shared/formbg_header" %>

  <div class="panel-heading">
    <h2> Nova Area </h2>
  </div>
  <div class="panel-body">

    <%= render 'form' %>

    <br>
    <%= link_to 'Voltar', areas_path, class: 'btn btn-link btn-sm' %>
  </div>

<%= render "shared/formbg_footer" %>

app/views/areas/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @area.name %>
</p>

<%= link_to 'Editar', edit_area_path(@area), class: 'btn btn-default btn-sm' %> |
<%= link_to 'Voltar', areas_path, class: 'btn btn-default btn-sm' %> |
<%= link_to 'Deletar', @area, class: 'btn btn-danger btn-sm', method: :delete, data: { confirm: 'Tem certeza?' } %>