config/routes.rb
Rails.application.routes.draw do

  resources :areas
  resources :category_types
  resources :courses do
    collection do
     get :search
     get :autocomplete
    end
  end
  resources :companies do
    resources :employees
  end

  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: "omniauth_callbacks" }

  root to: 'pages#index'
  get 'about'   => 'pages#about'
  get 'terms'   => 'pages#terms'
  get 'policy'   => 'pages#policy'
  get 'be_company' => 'pages#be_company'
  get 'faq'   => 'pages#faq'
  get 'support'   => 'pages#support'
  get 'steps'   => 'pages#steps'
end

app/controllers/category_types_controller.rb
class CategoryTypesController < ApplicationController
  before_action :set_category_type, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :owned_category, only: [:edit, :update, :destroy]

  # GET /category_types
  # GET /category_types.json
  def index
    @category_types = CategoryType.all
  end

  # GET /category_types/1
  # GET /category_types/1.json
  def show
  end

  # GET /category_types/new
  def new
    @category_type = CategoryType.new
  end

  # GET /category_types/1/edit
  def edit
  end

  # POST /category_types
  # POST /category_types.json
  def create
    @category_type = CategoryType.new(category_type_params)

    respond_to do |format|
      if @category_type.save
        format.html { redirect_to @category_type, notice: 'Categoria criada com sucesso.' }
        format.json { render :show, status: :created, location: @category_type }
      else
        format.html { render :new }
        format.json { render json: @category_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /category_types/1
  # PATCH/PUT /category_types/1.json
  def update
    respond_to do |format|
      if @category_type.update(category_type_params)
        format.html { redirect_to @category_type, notice: 'Categoria atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @category_type }
      else
        format.html { render :edit }
        format.json { render json: @category_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /category_types/1
  # DELETE /category_types/1.json
  def destroy
    @category_type.destroy
    respond_to do |format|
      format.html { redirect_to category_types_url, notice: 'Categoria apagada com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    def owned_category
      unless current_user.admin?
        flash[:alert] = "Somente administradores e usuários master podem editar as categorias"
        redirect_to root_path
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_category_type
      @category_type = CategoryType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_type_params
      params.require(:category_type).permit(:name, :category_id)
    end
end

app/helpers/category_types_helper.rb
module CategoryTypesHelper
end

app/views/category_types/_form.html.erb
<%= simple_form_for(@category_type) do |f| %>
  <%= f.error_notification %>
  <div class="form-group">
    <%= f.association :category %>
    <%= f.input :name %>
  </div>

  <br>
  <%= f.submit "Salvar", class: 'btn btn-primary form-control' %>
<% end %>

app/views/category_types/edit.html.erb
<%= render "shared/formbg_header" %>

  <div class="panel-heading">
    <h2> Editar Categoria </h2>
  </div>
  <div class="panel-body">

    <%= render 'form' %>

    <br>
    <%= link_to 'Exibir', @category_type, class: 'btn btn-link btn-sm' %>
    <%= link_to 'Voltar', category_types_path, class: 'btn btn-link btn-sm' %>
  </div>

<%= render "shared/formbg_footer" %>

app/views/category_types/index.html.erb
<h1>Categorias</h1>

<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Categoria</th>
      </tr>
    </thead>

    <tbody>
      <% @category_types.each do |category_type| %>
        <tr>
          <td><%= link_to category_type.name , category_type%></td>
          <td><%= category_type.category.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

<%= link_to "Nova Categoria",  new_category_type_path, class: 'btn btn-default btn-sm' %>

app/views/category_types/new.html.erb
<%= render "shared/formbg_header" %>

  <div class="panel-heading">
    <h2> Nova Categoria </h2>
  </div>
  <div class="panel-body">
    <%= render 'form' %>

    <br>
    <%= link_to 'Voltar', category_types_path, class: 'btn btn-link btn-sm' %>
  </div>

<%= render "shared/formbg_footer" %>

app/views/category_types/show.html.erb
<p>
  <strong>Categoria:</strong>
  <%= @category_type.category.name %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @category_type.name %>
</p>

<%= link_to 'Editar', edit_category_type_path(@category_type), class: 'btn btn-default btn-sm' %> |
<%= link_to 'Voltar', category_types_path, class: 'btn btn-default btn-sm' %> |
<%= link_to 'Deletar', @category_type, class: 'btn btn-danger btn-sm', method: :delete, data: { confirm: 'Tem certeza?' } %>