config/routes.rb
Rails.application.routes.draw do

  resources :areas
  resources :category_types
  resources :courses do
    collection do
     get :search
     get :autocomplete
    end
  end
  resources :companies do
    resources :employees
  end

  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: "omniauth_callbacks" }

  root to: 'pages#index'
  get 'about'   => 'pages#about'
  get 'terms'   => 'pages#terms'
  get 'policy'   => 'pages#policy'
  get 'be_company' => 'pages#be_company'
  get 'faq'   => 'pages#faq'
  get 'support'   => 'pages#support'
  get 'steps'   => 'pages#steps'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-12 social-footer">
        <div class="row">
          <div class="col-sm-1 col-sm-push-3 social-footer">
            <a href="https://www.facebook.com/seekatconcept/">
              <%= image_tag("icon-facebook.png", alt: "facebook", class: "img-responsive") %>
            </a>
          </div>
          <div class="col-sm-1 col-sm-push-3 social-footer">
            <a href="http://plus.google.com">
              <%= image_tag("icon-google.png", alt: "google+", class: "img-responsive") %>
            </a>
          </div>
          <div class="col-sm-1 col-sm-push-3 social-footer">
            <a href="https://twitter.com/seekatconcept">
              <%= image_tag("icon-twitter.png", alt: "twitter", class: "img-responsive") %>
            </a>
          </div>
          <div class="col-sm-1 col-sm-push-3 social-footer">
            <a href="https://www.youtube.com/channel/UCFwPwuNTWuwC17Azum3RO2w">
              <%= image_tag("icon-youtube.png", alt: "youtube", class: "img-responsive") %>
            </a>
          </div>
          <div class="col-sm-1 col-sm-push-3 social-footer">
            <a href="https://br.linkedin.com/in/seekat-concept-754b11115">
              <%= image_tag("icon-linkedin.png", alt: "linkedin", class: "img-responsive") %>
            </a>
          </div>
          <div class="col-sm-1 col-sm-push-3 social-footer">
            <a href="https://www.instagram.com/seekatconcept/">
              <%= image_tag("icon-instagram.png", alt: "instagram", class: "img-responsive") %>
            </a>
          </div>
        </div>
      </div>
    </div>
    <div class="row footer-links"> </div>
      <div class="row">
        <div class="col-sm-2 col-sm-push-3">
          <p class="about">SOBRE</p>
          <ul class="list-unstyled">
            <li><%= link_to "Quem somos",  about_path %></li>
            <li><%= link_to "Termos de uso",  terms_path %></li>
            <li><%= link_to "Política de privicidade",  policy_path %></li>
          </ul>
        </div>
        <div class="col-sm-2 col-sm-push-3">
          <p class="about">PARCEIROS</p>
          <ul class="list-unstyled">
            <li><%= link_to "Seja uma parceiro",  be_company_path %></li>
          </ul>
        </div>
        <div class="col-sm-2 col-sm-push-3">
          <p class="about">CONTATO</p>
          <ul class="list-unstyled">
            <li><%= link_to "Dúvidas frequentes", faq_path %></li>
            <li><%= link_to "Suporte", support_path %></li>
          </ul>
        </div>
      </div>
      <div class="row footer-links">
        <div class="row">
          <div class="col-sm-12 copyright">
            <p class="copyright"> Copyright © <%= Time.now.year %> Seekat &nbsp;
              Desenvolvido por <a href="https://github.com/jcvicelli/" target="_blank">Jean Carlo Vicelli</a>
              Design por <a href="https://github.com/lcampagnin/" target="_blank">Luciane Campagnin</a>
            </p>
          </div>
        </div>
      </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to(image_tag("marca-seeakat.png", alt: "Seekat", class: 'navbar-brand') , root_path) %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to raw('<span class="glyphicon glyphicon-home"></span> Home'),   root_path %></li>
        <li><%= link_to "Divulgue seu curso!", steps_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <span class="glyphicon glyphicon-user"></span>
              <%= current_user.name %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Minha Conta', edit_user_registration_path %></li>
              <li><%= link_to 'Parceiros', companies_path %></li>
              <li><%= link_to 'Cursos | Eventos', courses_path %></li>
              <% if current_user.admin? %>
                <li><%= link_to 'Categorias', category_types_path %></li>
                <li><%= link_to 'Areas', areas_path %></li>
              <% end %>
              <li class="divider"></li>
              <li><%= link_to raw('<span class="glyphicon glyphicon-log-out"></span> Log out'), destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to raw('<span class="glyphicon glyphicon-user"></span> Criar Conta'), new_user_registration_path %></li>
          <li><%= link_to raw('<span class="glyphicon glyphicon-log-in"></span> Log in'), new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_home_center.html.erb
  <!-- cursos -->
  <br>
  <div class="container">
    <div class="row row-search">
      <%= form_tag search_courses_path,  class: 'form', method: 'get' do %>
        <div class="col-md-10">
          <div class="form-group">
            <%= text_field_tag :q, params[:q], class: 'input-lg form-control', placeholder: 'Buscar...', id: "course_search", autocomplete: "off" %>
          </div>
        </div>
        <div class="col-md-2">
          <%= submit_tag "Buscar", class: "btn btn-lg btn-block btn-search-home from-control" %>
        </div>
      <% end %>
    </div>

    <br>
    <div class="row">
      <div class="col-sm-12">
        <p class="home-titles">Confira os destaques da semana</P>
      </div>
    </div>

    <br>

    <div class="row">
      <div class="col-sm-12">
        <div class="thumbnail thumb-big">
          <a href="https://www.udemy.com/criar-ebook/">
            <%= image_tag("courses/adv-big-ebook.jpg", alt: "thumbnail", class: "img-responsive") %>
            <div class="caption">
              <p class="adv-big">Aprenda como criar um eBook</p>
            </div>
          </a>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-12">
        <p class="home-titles">Outros destaques</p>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-4">
        <div class="thumbnail thumb-med">
          <a href="http://www.veduca.com.br/cursos/gratuitos/energias-renovaveis">
            <%= image_tag("courses/03_adv-medium.jpg", alt: "thumbnail", class: "img-responsive") %>
            <div class="caption">
              <p class="adv-medium">Programa para geração e uso de energias limpas na América Latina</p>
            </div>
          </a>
        </div>
      </div>

      <div class="col-sm-4">
        <div class="thumbnail thumb-med">
          <a href="http://www.veduca.com.br/cursos/gratuitos/google-adwords">
            <%= image_tag("courses/02_adv-medium.jpg", alt: "thumbnail", class: "img-responsive") %>
            <div class="caption">
              <p class="adv-medium">Aprenda a utilizar o Google AdWords</p>
            </div>
          </a>
        </div>
      </div>

      <div class="col-sm-4">
        <div class="thumbnail thumb-med">
          <a href="http://www3.veduca.com.br/cursos/extensao/ensino-hibrido-personalizacao-e-tecnologia-na-educacao">
            <%= image_tag("courses/04_adv-medium.jpg", alt: "thumbnail", class: "img-responsive") %>
            <div class="caption">
              <p class="adv-medium">Ensino híbrido: personalização e tecnologia na educação</p>
            </div>
          </a>
        </div>
      </div>

      <div class="col-sm-4">
        <div class="thumbnail thumb-med">
          <a href="https://www.edx.org/course/implementing-customer-insights-business-delftx-idemc-1x">
            <%= image_tag("courses/05_adv-medium.jpg", alt: "thumbnail", class: "img-responsive") %>
            <div class="caption">
              <p class="adv-medium">Implementing Customer Insights for Your Business</p>
            </div>
          </a>
        </div>
      </div>

      <div class="col-sm-4">
        <div class="thumbnail thumb-med">
          <a href="http://www.veduca.com.br/cursos/gratuitos/financas-pessoais-e-investimento-em-acoes">
            <%= image_tag("courses/06_adv-medium.jpg", alt: "thumbnail", class: "img-responsive") %>
            <div class="caption">
              <p class="adv-medium">Finanças pessoais e Investimentos em Ações  BMF & BOVESPA</p>
            </div>
          </a>
        </div>
      </div>

      <div class="col-sm-4">
        <div class="thumbnail thumb-med">
          <a href="https://www.udemy.com/brackets-edge-code/">
            <%= image_tag("courses/01_adv-medium.jpg", alt: "thumbnail", class: "img-responsive") %>
            <div class="caption">
              <p class="adv-medium">Brackets & Edge Code  Fundamentos</p>
            </div>
          </a>
        </div>
      </div>

    <br>

    <div class="row">
      <div class="col-sm-4"></div>
      <div class="col-sm-4">
        <button type="button" class="btn btn-primary-highlights">TODOS OS EVENTOS</button>
      </div>
      <div class="col-sm-4"></div>
    </div>

      <br>

      <div class="row">
        <div class="col-sm-12">
          <p class="home-titles">Divulgue sua empresa e promova seus eventos</P>
        </div>
      </div>

      <br>

      <div class="col-sm-3">
        <div class="thumbnail thumb-small">
          <%= image_tag("courses/adv-01.jpg", alt: "adv", class: "img-responsive") %>
        </div>
      </div>

      <div class="col-sm-3">
        <div class="thumbnail thumb-small">
          <%= image_tag("courses/adv-02.jpg", alt: "adv", class: "img-responsive") %>
        </div>
      </div>

      <div class="col-sm-3">
        <div class="thumbnail thumb-small">
          <%= image_tag("courses/adv-03.jpg", alt: "adv", class: "img-responsive") %>
        </div>
      </div>

      <div class="col-sm-3">
        <div class="thumbnail thumb-small">
          <%= image_tag("courses/adv-04.jpg", alt: "adv", class: "img-responsive") %>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-4"></div>
        <div class="col-sm-4">
          <button type="button" class="btn btn-primary-highlights">TODOS OS PARCEIROS</button>
        </div>
        <div class="col-sm-4"></div>
      </div>

      <br>
      <br>

    </div>
  </div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Seekat</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.9.3/typeahead.min.js" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= favicon_link_tag 'favicon.ico' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  </head>
  <body>
    <%= render 'layouts/header' %>

    <div class="container-fluid">
      <div class="row">
        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <%= value %>
          </div>
        <% end %>
      </div>
      <%= yield :top_content %>
    </div>

    <%= yield %>


    <%= render 'layouts/footer' %>

  </body>
</html>